### ISSUE TITLE
Compile fails with v2.4.0

### ISSUE THREAD

**Issue by kankaristo** [svenstaro/rofi-calc#141]
The build is failing for me with v2.4.0 (works with v2.3.3):
```
> meson compile -C build/
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /tmp/rofi/calc/build
ninja: Entering directory `/tmp/rofi/calc/build'
[1/2] Compiling C object src/libcalc.so.p/calc.c.o
FAILED: src/libcalc.so.p/calc.c.o
cc -Isrc/libcalc.so.p -Isrc -I../src -I/usr/include/ -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/cairo -I/usr/inclu
de/libpng16 -I/usr/include/freetype2 -I/usr/include/pixman-1 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -O0 -g -Winline -Wunreachable-
code -fPIC -pthread -MD -MQ src/libcalc.so.p/calc.c.o -MF src/libcalc.so.p/calc.c.o.d -o src/libcalc.so.p/calc.c.o -c ../src/calc.c
../src/calc.c: In function ‘set_config’:
../src/calc.c:260:5: error: unknown type name ‘ConfigEntry’
  260 |     ConfigEntry *config_file = rofi_config_find_widget(sw->name, NULL, TRUE);
      |     ^~~~~~~~~~~
../src/calc.c:260:32: error: implicit declaration of function ‘rofi_config_find_widget’ [-Wimplicit-function-declaration]
  260 |     ConfigEntry *config_file = rofi_config_find_widget(sw->name, NULL, TRUE);
      |                                ^~~~~~~~~~~~~~~~~~~~~~~
../src/calc.c:260:32: error: initialization of ‘int *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
../src/calc.c:275:29: error: implicit declaration of function ‘rofi_theme_find_property’ [-Wimplicit-function-declaration]
  275 |         Property *no_bold = rofi_theme_find_property(config_file, P_BOOLEAN,
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~
../src/calc.c:275:29: error: initialization of ‘Property *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
../src/calc.c:281:27: error: initialization of ‘Property *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  281 |         Property *terse = rofi_theme_find_property(config_file, P_BOOLEAN,
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~
../src/calc.c:287:32: error: initialization of ‘Property *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  287 |         Property *no_unicode = rofi_theme_find_property(
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~
../src/calc.c:293:32: error: initialization of ‘Property *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  293 |         Property *cmd_option = rofi_theme_find_property(
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~
../src/calc.c:300:40: error: initialization of ‘Property *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  300 |         Property *hint_result_option = rofi_theme_find_property(
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~
../src/calc.c:308:41: error: initialization of ‘Property *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  308 |         Property *hint_welcome_option = rofi_theme_find_property(
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~
../src/calc.c:316:45: error: initialization of ‘Property *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  316 |         Property *calc_error_color_option = rofi_theme_find_property(
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~
../src/calc.c:324:32: error: initialization of ‘Property *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  324 |         Property *no_history = rofi_theme_find_property(
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~
../src/calc.c:330:40: error: initialization of ‘Property *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  330 |         Property *no_persist_history = rofi_theme_find_property(
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~
../src/calc.c:337:47: error: initialization of ‘Property *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  337 |         Property *automatic_save_to_history = rofi_theme_find_property(
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~
../src/calc.c:345:47: error: initialization of ‘Property *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  345 |         Property *calc_command_uses_history = rofi_theme_find_property(
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```

**Comment by kankaristo** [comment]
Ah, that's most likely the reason, I'm on Rofi 1.7.5. I'll close the issue.
